// <auto-generated />
using FurnitureStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240329165218_AddStockToProduct")]
    partial class AddStockToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurnitureStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailableForPurchase")
                        .HasColumnType("bit");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Chairs",
                            Description = "High-back executive office chair with ergonomic design",
                            ImageUrl = "",
                            IsAvailableForPurchase = true,
                            ListPrice = 250.0,
                            Manufacturer = "Manufacturer X",
                            Name = "Executive Office Chair",
                            Price = 199.99000000000001,
                            ProductId = "CH001",
                            Stock = 0,
                            Supplier = "Supplier A"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tables",
                            Description = "Large rectangular conference table with wooden finish",
                            ImageUrl = "",
                            IsAvailableForPurchase = true,
                            ListPrice = 800.0,
                            Manufacturer = "Manufacturer Y",
                            Name = "Conference Table",
                            Price = 649.99000000000001,
                            ProductId = "TB002",
                            Stock = 0,
                            Supplier = "Supplier B"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Shelves",
                            Description = "Tall wooden bookshelf with adjustable shelves",
                            ImageUrl = "",
                            IsAvailableForPurchase = true,
                            ListPrice = 180.0,
                            Manufacturer = "Manufacturer Z",
                            Name = "Bookshelf",
                            Price = 149.99000000000001,
                            ProductId = "SH003",
                            Stock = 0,
                            Supplier = "Supplier C"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Workstations",
                            Description = "Compact computer workstation with keyboard tray",
                            ImageUrl = "",
                            IsAvailableForPurchase = true,
                            ListPrice = 300.0,
                            Manufacturer = "Manufacturer W",
                            Name = "Computer Workstation",
                            Price = 249.99000000000001,
                            ProductId = "WS004",
                            Stock = 0,
                            Supplier = "Supplier D"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Chairs",
                            Description = "Mesh-back office chair with lumbar support",
                            ImageUrl = "",
                            IsAvailableForPurchase = true,
                            ListPrice = 150.0,
                            Manufacturer = "Manufacturer Q",
                            Name = "Mesh Office Chair",
                            Price = 119.98999999999999,
                            ProductId = "CH005",
                            Stock = 0,
                            Supplier = "Supplier E"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
